spring:
  datasource:
    name: springbootdemo
   # url: jdbc:mysql://192.168.4.136:3306/springbootdemo?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.4.136:3306/springbootdemo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: handkoo
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 192.168.4.51  # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:  #Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0

## 该配置节点为独立的节点，千万别将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.handkoo.springbootmybatis.bean  # 注意：对应实体类的路径

  #pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志配置
logging:
  config: classpath:log/logback-spring.xml


